export const projects = [
    {
        title: "Velora Estates",
        description: "A luxury real estate single-page application built with Next.js, Framer Motion, and Lenis smooth-scrolling. Features scroll-spy navigation, an asymmetric gallery layout, and a WhatsApp-based consultation flow designed to convert visitors into leads without a heavy contact form.",
        stack: ["Next.js", "Tailwind CSS", "Motion"],
        previewLink: "https://velora-real-estate-byma.vercel.app/",
        sourceLink: "https://github.com/MuhammadAunR/Velora-Real-Estate.git",
        image: "/p11-velora.webp",
    },
    {
        title: "Odour",
        description: "A scalable e-commerce solution that helps perfume brands showcase products, streamline online sales, and deliver a seamless shopping experience through optimized product discovery and modern web performance. 🛍️",
        stack: ["Next.js", "Tailwind", "Framer-Motion", "Node.js"],
        previewLink: "https://odour-byma.vercel.app/",
        sourceLink: "https://github.com/MuhammadAunR/Odour",
        image: "/p10-odour.webp",
    },
    {
        title: "Larizo",
        description: "A luxury fragrance brand site designed and built from scratch — premium typography, smooth Framer Motion transitions, and a mobile-first layout crafted to make the brand feel expensive from the first scroll.",
        stack: ["Next.js", "Framer Motion", "Tailwind"],
        previewLink: "https://larizo.vercel.app/",
        sourceLink: "https://github.com/MuhammadAunR/Larizo",
        image: "/p9-larizo.webp",
    },
    {
        title: "Fuoco",
        description: "Redesigned Fuoco's brand website from Figma — elevated visual identity, mobile-optimized layout, and a premium feel that matches the brand's personality. 🔥",
        stack: ["Next.js", "Tailwind"],
        previewLink: "https://fuoco-restaurants-byma.vercel.app/",
        sourceLink: "https://github.com/MuhammadAunR/Fuoco-Restaurants",
        image: "/p8-fuoco.webp",
    },
    {
        title: "Creator Portfolio",
        description: "A cinematic portfolio for a content creator — optimized video loading, smooth Lenis scrolling, and a visual-first layout built to impress clients. 🎥",
        stack: ["React.js", "Tailwind", "Context API", "Lenis"],
        previewLink: "https://portfolio-content-creator-byma.vercel.app/",
        sourceLink: "https://github.com/MuhammadAunR/Portfolio-Content-Creator",
        image: "/p6-portfolio-creator.webp",
    },
    // {
    //     title: "DMR Sushi",
    //     description: "Restaurant website with interactive menu browsing, food ordering, and table reservations — reducing friction between hungry customers and the dining experience. 🍣",
    //     stack: ["Next.js", "Tailwind", "Context API", "Lenis", "AOS"],
    //     previewLink: "https://restaurant-website-byma.vercel.app/",
    //     sourceLink: "https://github.com/MuhammadAunR/Restaurant-Website",
    //     image: "/p7-restaurant-website.webp",
    // },
    // {
    //     title: "Shop.CO",
    //     description: "A complete e-commerce platform with CMS-powered product management, cart system, and scalable backend — built for real retail operations. 🛍️",
    //     stack: ["Next.js", "Tailwind", "Strapi", "Node.js"],
    //     previewLink: "",
    //     sourceLink: "https://github.com/MuhammadAunR/E-Commerce-Store",
    //     image: "/p2-e-store.webp",
    // },
    // {
    //     title: "Tripzo",
    //     description: "A travel booking platform with destination discovery, trip planning, and seamless experience booking — designed to convert visitors into customers. 🚞",
    //     stack: ["React.js", "Tailwind"],
    //     previewLink: "https://tripzo-byma.vercel.app/",
    //     sourceLink: "https://github.com/MuhammadAunR/Tripzo",
    //     image: "/p3-tripzo.webp",
    // },
    // {
    //     title: "Flavor Fiesta",
    //     description: "A recipe-sharing platform built for engagement — users discover, save, and share recipes with a fast, animated UI that keeps them coming back. 🧑🏻‍🍳",
    //     stack: ["React.js", "Tailwind", "JS-AOS"],
    //     previewLink: "https://flavor-fiesta-byma.vercel.app/",
    //     sourceLink: "https://github.com/MuhammadAunR/Flavor-Fiesta",
    //     image: "/p4-cooking.webp",
    // },
    // {
    //     title: "Buddy Chat",
    //     description: "An AI-powered chatbot integrated with GROQ API — real-time responses, clean chat UI, and context-aware conversations for any web product. 🤖",
    //     stack: ["React.js", "Tailwind", "Context API", "GROQ API"],
    //     previewLink: "https://buddy-chat-byma.vercel.app/",
    //     sourceLink: "https://github.com/MuhammadAunR/Buddy-Chat",
    //     image: "/p5-buddyChat.webp",
    // },
    // {
    //     title: "Coffee Shop",
    //     description: "Built a full online ordering experience for a coffee brand — mobile-first design with menu browsing and a smooth checkout flow to drive online sales. ☕",
    //     stack: ["Next.js", "Tailwind"],
    //     previewLink: "https://coffeeshop-7ad9.vercel.app/",
    //     sourceLink: "https://github.com/MuhammadAunR/Coffee-Shop",
    //     image: "/p1-coffeeshop.webp",
    // },
];