export const projects = [
    {
        title: "Coffee Shop",
        description: "Built a full online ordering experience for a coffee brand — mobile-first design with menu browsing and a smooth checkout flow to drive online sales. ☕",
        stack: ["Next.js", "Tailwind"],
        previewLink: "https://coffeeshop-7ad9.vercel.app/",
        sourceLink: "https://github.com/MuhammadAunR/Coffee-Shop",
        image: "/p1-coffeeshop.webp",
    },
    {
        title: "Shop.CO",
        description: "A complete e-commerce platform with CMS-powered product management, cart system, and scalable backend — built for real retail operations. 🛍️",
        stack: ["Next.js", "Tailwind", "Strapi", "Node.js"],
        previewLink: "",
        sourceLink: "https://github.com/MuhammadAunR/E-Commerce-Store",
        image: "/p2-e-store.webp",
    },
    {
        title: "Tripzo",
        description: "A travel booking platform with destination discovery, trip planning, and seamless experience booking — designed to convert visitors into customers. 🚞",
        stack: ["React.js", "Tailwind"],
        previewLink: "https://tripzo-byma.vercel.app/",
        sourceLink: "https://github.com/MuhammadAunR/Tripzo",
        image: "/p3-tripzo.webp",
    },
    {
        title: "Flavor Fiesta",
        description: "A recipe-sharing platform built for engagement — users discover, save, and share recipes with a fast, animated UI that keeps them coming back. 🧑🏻‍🍳",
        stack: ["React.js", "Tailwind", "JS-AOS"],
        previewLink: "https://flavor-fiesta-byma.vercel.app/",
        sourceLink: "https://github.com/MuhammadAunR/Flavor-Fiesta",
        image: "/p4-cooking.webp",
    },
    {
        title: "Buddy Chat",
        description: "An AI-powered chatbot integrated with GROQ API — real-time responses, clean chat UI, and context-aware conversations for any web product. 🤖",
        stack: ["React.js", "Tailwind", "Context API", "GROQ API"],
        previewLink: "https://buddy-chat-byma.vercel.app/",
        sourceLink: "https://github.com/MuhammadAunR/Buddy-Chat",
        image: "/p5-buddyChat.webp",
    },
    {
        title: "Creator Portfolio",
        description: "A cinematic portfolio for a content creator — optimized video loading, smooth Lenis scrolling, and a visual-first layout built to impress clients. 🎥",
        stack: ["React.js", "Tailwind", "Context API", "Lenis"],
        previewLink: "https://portfolio-content-creator-byma.vercel.app/",
        sourceLink: "https://github.com/MuhammadAunR/Portfolio-Content-Creator",
        image: "/p6-portfolio-creator.webp",
    },
    {
        title: "DMR Sushi",
        description: "Restaurant website with interactive menu browsing, food ordering, and table reservations — reducing friction between hungry customers and the dining experience. 🍣",
        stack: ["Next.js", "Tailwind", "Context API", "Lenis", "AOS"],
        previewLink: "https://restaurant-website-byma.vercel.app/",
        sourceLink: "https://github.com/MuhammadAunR/Restaurant-Website",
        image: "/p7-restaurant-website.webp",
    },
    {
        title: "Fuoco",
        description: "Redesigned Fuoco's brand website from Figma — elevated visual identity, mobile-optimized layout, and a premium feel that matches the brand's personality. 🔥",
        stack: ["Next.js", "Tailwind"],
        previewLink: "https://fuoco-restaurants-byma.vercel.app/",
        sourceLink: "https://github.com/MuhammadAunR/Fuoco-Restaurants",
        image: "/p8-fuoco.webp",
    },
];